#!/bin/bash

# Make sure that the SLPI DSP test signature is there otherwise px4 cannot run
# on the DSP
if /bin/ls /usr/lib/rfsa/adsp/testsig-*.so &> /dev/null; then
    /bin/echo "Found DSP signature file"
else
    /bin/echo "Error, could not find DSP signature file"
    exit 0
fi

DAEMON=" "

while getopts d flag
do
    case "${flag}" in
        d) DAEMON="-d";;
    esac
done

if [ ! -f /data/px4/param/parameters ]; then
   echo "Setting default parameters for PX4 on voxl"
   px4 $DAEMON -s /etc/modalai/voxl-px4-set-default-parameters.config
   /bin/sync
fi

px4 $DAEMON -s /etc/modalai/voxl-px4.config
