#!/bin/sh
# (px4-alias.sh is expected to be in the PATH)
#!/bin/bash
  
# Make sure that the SLPI DSP test signature is there otherwise px4 cannot run
# on the DSP
if /bin/ls /usr/lib/rfsa/adsp/testsig-*.so &> /dev/null; then
    /bin/echo "Found DSP signature file"
else
    /bin/echo "Error, could not find DSP signature file"
    exit 0
fi

# Export minimal px4 to run everything in one contained file
export MINIMAL_PX4=1

# Setup system for VIO usage
VIO=0
DAEMON=" "
while getopts vd flag
do
    case "${flag}" in
	v) VIO=1 ;;
    	d) DAEMON="-d" ;;
    esac
done

if [ $VIO == 1 ]; then
   echo "Setting VIO Parameters for HITL"
   sed -i '/qshell modalai_dsp start/c\qshell modalai_dsp start -v' /etc/modalai/voxl-px4-hitl.config
   px4 $DAEMON -s /etc/modalai/voxl-px4-hitl-vio-parameters.config
   /bin/sync
else
   echo "Setting GPS Parameters for HITL"
   sed -i '/qshell modalai_dsp start/c\qshell modalai_dsp start' /etc/modalai/voxl-px4-hitl.config   
   px4 $DAEMON -s /etc/modalai/voxl-px4-hitl-gps-parameters.config
   /bin/sync
fi

px4 $DAEMON -s /etc/modalai/voxl-px4-hitl.config                                       
